version: "3"

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - ./db_data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_PSQL_USER}" ]
      interval: 10s
      retries: 5
      timeout: 10s


  web:
    container_name: djoser-learning
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
